"""empty message

Revision ID: 31279dec437f
Revises: None
Create Date: 2014-06-16 21:58:36.302116

"""

# revision identifiers, used by Alembic.
revision = '31279dec437f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
